services:
  target-architecture:
    container_name: software-architecture-documentation-target
    image: structurizr/lite
    volumes:
      - ./base:/usr/local/base
      - ./target:/usr/local/structurizr
    ports:
      - "8081:8080"

#  baseline-architecture:
#    container_name: software-architecture-documentation-baseline
#    image: structurizr/lite
#    volumes:
#      - ./workspace:/usr/local/structurizr
#    ports:
#      - "8082:8080"

  # Examples
  internet-banking-system:
    container_name: internet-banking-system
    image: structurizr/lite
    volumes:
      - ./base:/usr/local/base
      - ./examples/internet-banking-system:/usr/local/structurizr
    ports:
      - "8083:8080"

  base:
    container_name: base-architecture
    image: structurizr/lite
    volumes:
      - ./base:/usr/local/structurizr
    ports:
      - "8080:8080"        